[package]
name = "hello-rust-api"
version = "0.1.0"
edition = "2018"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
warp = "0.3"
config = "0.11"
lazy_static = "1.4.0"
log="0.4.14"
env_logger="0.8.4"
